### ISSUE TITLE
1:10 Form:  Multiple complaint forms generated from single submission sent to program area

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1040]
As a program area, we need individual complaint forms submitted for accurate reporting and information with complainant.  

Form owner reported the following details

- On April 12 (11:28) received a new 1.10 complaint (generated from formsflow tool to the program area inbox) 
- 11:28 received a second
- 11:29 I received a third  

Form owner reported that all three were identical and confirmed with the Complainant that she only submitted one complaint.

**Comment by Stella-Archer** [comment]
Don can be contacted at > Don.Smallwood@gov.bc.ca

**Comment by iman-jamali-fw** [comment]
I looked at this issue, the submission that originally was sent on April 12, was reported by Camunda as having an issue with sending emails to the PSA mailbox, so as the first debugging step, I simply ran that step (again) in the workflow, which apparently has triggered two extra emails to the mailbox, sorry about that! Please ignore those extra emails.
 
I am currently investigating the root cause of the issue that caused the submission to become stuck in the workflow.

**Comment by EduardoRamirezBC** [comment]
How do we future proof to prevent this from happening?

**Comment by MeghanStothers** [comment]
Form owner reported an ongoing issue - he received the same submission three times.

**Comment by iman-jamali-fw** [comment]
There was another incident reported yesterday. It doesn't impact the user, but the submission gets stuck at the last stage of the workflow and won't be removed from the platform (the last stage auto removes the submission).

**Comment by iman-jamali-fw** [comment]
There was another incident reported yesterday. It doesn't impact the user, but the submission gets stuck at the last stage of the workflow and won't be removed from the platform (the last stage auto removes the submission).

**Comment by fazil-ey** [comment]
Don's team should not be getting multiple duplicate emails. But the submission is till in camunda and may be a violation of PIA. Therefore the scope of this ticket is fixed.
