### ISSUE TITLE
Telework form layout/design fixes

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#106]
Please address the following issues:

1. More padding is needed on the left side of the logo
2. Spacing between the logo and title on the header should be reduced to match the one on the BC gov site.
3. Upon tab click, the navbar bottom tab border should be underlined in yellow to match the BC gov site.  
Please see the screenshot, top view is what we have on dev and bottom is what is on BC Gov site. 
![devVsBC.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/a9406374-4b2c-4661-ac6d-27521899831a)

4. 11 contrast errors on Telework form found using Wave tool.

5.  Button alignments should be consistent.
![buttonAlignment.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/03c1a5ba-217b-4f0d-9831-0242661aec04)

5. Edit and Next button text should be aligned in consistency with the other button texts.
![editButton.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/9e286da5-d796-4e11-a53c-f6b95fb3fef4)

**Comment by Abuchana** [comment]
Needs to be reviewed on the current version as these screen shots are dated, waiting for the blockers to be be removed first

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/3251e626-fae5-46a1-9a84-958ab22b43b0)yes the logo should have about 15px padding on th eleft, but this could wait til we get the WIW logo in #165

**Comment by david-sabadash** [comment]
Update to AC: ensure the correct Favicon is in TEST

**Comment by david-sabadash** [comment]
@Stella-Archer just wanted your feedback on this, i managed to get the new logo working (and tested in DEV, no longer breaking the environments)

Img 1: shows the logo in-line vertically with the navigation tabs, matching the left hand side padding, and with reduced space between the logo and the Digital Journeys text.
Also added a very slight padding around the top and bottom of the WIW logo, otherwise the WIW text looked kindof smushed against the bottom of the navigation bar
![image.png](https://images.zenhubusercontent.com/62b33d00d955ad0dc2151a98/06df4550-29c4-402c-a6af-152647a28cdc)

Img 2:
same as above, except with an increased left-hand side margin, more closely resembling the other BC Gov website mentioned in the ticket AC
![image.png](https://images.zenhubusercontent.com/62b33d00d955ad0dc2151a98/73f3aae1-fa2d-4419-b05f-ab59dad1cf2a)

**Comment by david-sabadash** [comment]
only real 'style complaint' that i have is that the WIW text is bottom-justified whereas the DJ text is center-justified. Not a huge thing, just bugs me.

**Comment by Stella-Archer** [comment]
yeah it would be great to get them working together a bit better

**Comment by david-sabadash** [comment]
Thoughts? it was a lot easier to edit the logo than it was to move the DJ text
![image.png](https://images.zenhubusercontent.com/62b33d00d955ad0dc2151a98/78469d46-dca5-420c-9141-7e75b8aab95a)

**Comment by Stella-Archer** [comment]
that looks amazing!

**Comment by Stella-Archer** [comment]
Oh Nooo turns out we cant change anything about the logo so don't worry about tplavement just go back to thhe unaltered version of WIW :( ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/6b51cdd0-9456-4c9e-96c6-6bafe9f2c6c4)

**Comment by david-sabadash** [comment]
Ahh my apologies. Exactly why i wanted to pass it by you before committing  any changes. Thanks for the feedback!

**Comment by HasanSifat** [comment]
Tested successfully in DEV & TEST 

Ready to be transferred to PROD

**Comment by HasanSifat** [comment]
Tested successfully in PROD!
