### ISSUE TITLE
Cold/Flu: Retention of forms in tool (2024 Cycle)

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1071]
As a program area, each form will need a specified retention date at which the forms will be removed from the formsflow.ai platform.

(A/C)
- get dates when form is open - June 10, 2024
- get date when form is closed - Soft close June 28, 2024, but form should be visible, July 15, 2024 should only be open for admins 
 
- consult with business area to consider their business needs 
    - Retain submitted forms till DD/MM/2025, implement this manually because we don't know if the process will be the same every year yet 
    - Retain drafts - 60 days
- Ensure these dates are reflected in the PIAS for Digital Journeys, as well as for the one Cold and Flu 
- estimate and assign technical work

**Comment by MeghanStothers** [comment]
Discussion needed about how we turn/off and turn on reminders for these types of tickets - automation opportunity?

**Comment by Stella-Archer** [comment]
discuss 2024 retention/clean out dates with heather

**Comment by Augusteen-myeong** [comment]
> @Augusteen-myeong could you discuss the 2024 schedule/retention/clean out dates with Heather
> 
> * June 10-28, 2024 Registration Period Form is open, Link is LiVE on the Careers & MyHR Site
> * June 28 - July 12 "buffer" period Form is open, Link is REMOVED from the Careers & MyHR Site
> * [ ]  Heather/Admin access dates?
> * [ ]  Retain submitted forms till DD/MM/YYYY?,
> * [ ]   implement this manually because we don't know if the process will be the same every year yet ?
> * [ ]  Retain drafts - 60 days, but will be implemented in a different ticket [Unsubmitted Draft Retention #992](https://github.com/bcgov/digital-journeys/issues/992)
> * [ ]  Ensure these dates are reflected in the PIAS for Digital Journeys, as well as for the one Cold and Flu



### Answers to your questions @Stella-Archer  
**Heather/Admin access dates?** 
- Heather needs access to the form from June through November.
- Admin will need access to the form the whole time. Same as the past year - They still have access now

**Retain submitted forms till DD/MM/YYYY?**
- January 2025

**Implement this manually because we don't know if the process will be the same every year yet ?**
- [Question] Do you mean we could launch the form automatically every year as long as we don't make any changes? Do we want to check with her if it'd be okay to automate the form launch process starting 2025?

**Retain drafts - 60 days, but will be implemented in a different ticket Unsubmitted Draft Retention #992**
- [Question] Was this also a question for Heather? Do we want to make sure Heather agrees on 60 days of the retention cycle? 

**Ensure these dates are reflected in the PIAS for Digital Journeys, as well as for the one Cold and Flu**
- [Question] I assume it wasn't a question for Heather. Would you like me to update the dates on PIA once we finalize all the dates?

**Comment by MeghanStothers** [comment]
@Stella-Archer The 2024 schedule/launch dates maybe impacted by the OCI migration, tentatively set for early May, although likely to change "by a month or so."  

Suggesting here that Heather is made aware of this migration, and I'll keep you up to date on any developments and I'd also suggest keeping in contact with Patrick about the migration plans, too.

**Comment by Stella-Archer** [comment]
Thanks Meghan, good call on the OCI impacts, @Augusteen-myeong we are starting to test those in the DEV environment  this week #1666 describes this. I will talk to @jerry-ey to see if he can add you to the DEV C&F Admin so you can have an early look at and test for any issues with this form and the new OCI endpoints. Dev also has a new version of the App so also a great idea to have your eyes in there for any changes impact to Cold & Flu

**Comment by jerry-ey** [comment]
@Augusteen-myeong  could you please login to DEV (https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form) first with your IDIR, so that I can find your user info in the backend?

**Comment by Augusteen-myeong** [comment]
@jerry-ey - I've logged in with my IDIR with the link you provided. This is what I see: 
![image](https://github.com/bcgov/digital-journeys/assets/159492049/cd3f7387-b59b-4a6d-98e7-55aecee83d37)

**Comment by Stella-Archer** [comment]
Aha the Release notes! @fazil-ey I think it's fine to have the content of the message when one 1st logs in but we need to change the title form "Release Notes November, 2022" do you have any suggestions?
