### ISSUE TITLE
Cold/Flu - Pre populate worksite contact details 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1090]
**User Story**
As a registrant I want my details to be pre-filled in the form using my IDIR login details so that I do not have to type it out again

**AC**
- [ ] The worksite contact fields must be pre-filled when adding a new registration or worksite
- [ ] The worksite contact fields must be editable & existing validation rules must be applied

**Comment by iman-jamali-fw** [comment]
Can we clarify if this functionality works only when a regular user registers? 

@bhumin-fw 
Can we populate the fields using the logged-in user's employee data?

**Comment by bhumin-fw** [comment]
@iman-jamali-fw we can clarify that for sure.

Data are already pre-populate using ODS employee API. Primary first_name, last name, email and phone.

**Comment by Stella-Archer** [comment]
@bhumin-fw the worksite contact flied has to be editable incase the users name or phone number has changed or is incorrect 
There is also an issue with the phone number in TEST right now.
For my info it's serving up my personal/home cell not my work number and the it's pulling is adding a '1' in formnt of it
My cell is 1 250-704-8780 this is how it appears in TEST
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/38db10c1-c7c6-48bd-8f1e-76eecf944b78)

**Comment by bhumin-fw** [comment]
@Stella-Archer 
I did review your object IDIR/GUID.
your office_phone has ""(blank) value, that's why it picks "phone" from the same object. It is your personal number that't the only ph we are retrieving from ODS API.

Updated below points,
- corrected: remove 1 as prefix.
- enable field for all user so they can edit it.
- load all four field, based on ODS object values.

**Comment by Stella-Archer** [comment]
thanks @bhumin-fw  edit function is working but still getting an error on the Pre-pop phone number
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/e9439f4d-915e-4034-9497-433bc6f4db64)

**Comment by bhumin-fw** [comment]
@Stella-Archer 
I was fixing issue to load value in formatted component, that's why you saw error on that component. It's done. This issue is fixed in DEV and TEST env.

Please go ahead and start testing this ticket now. 
And Thank you so much to check it a bit early and provide additional feedback. Much appreciate :)

**Comment by ayushdamani** [comment]
Tested and verified working ✔️

The worksite contact fields must be pre-filled when adding a new registration or worksite
![Screenshot 2023-05-09 134410.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/b3dc6d4d-c81d-4b52-9c30-b45f5d357fa0)

The worksite contact fields is editable & existing validation rules are applied
![Screenshot 2023-05-09 134527.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/cc19b8a2-f3b7-4645-a90c-415fa2328488)
