### ISSUE TITLE
Include Telework Agreement's submitted form link in submitter's email

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#122]
**Description**: As a user, I want to see a link to my submission in the e-mail I receive after submitting my application.

**Acceptance Criteria**
- The form submitter should receive an e-mail (entered in the Employee E-mail field while filling out the form) upon form submission that includes a link to the submitted application.

**Comment by MeghanStothers** [comment]
Let's confirm at May 26 srum this ticket can be closed @Stella-Archer

**Comment by DonMoffatt** [comment]
It was suggested that the link the manager receives be added to the message the employee receives. However, because this points to a task, and the task disappears after the manager completes it, this would be confusing and of little value to the employee.  The section they completed is greyed out and they do not see the supervisor portion at this point. The employee can already see a copy online and receives a PDF artifact of what they submitted, so offering this view has no added value. As a result, @Stella-Archer and I decided not to add the link to the employee email.

**Comment by DonMoffatt** [comment]
@Stella-Archer  and I also discussed the possibility of including a link to the Applications tab, or additional messaging. However, we thought that this is likely overkill as there is other messaging and copies of the form.  As a results we are closing the ticket. If user testing reveals a justification for a message there we can revisit the topic.
