### ISSUE TITLE
Explore: Migration to the new AOT deployment - Helm Chart-based

### ISSUE THREAD

**Issue by iman-jamali-fw** [bcgov/digital-journeys#1236]
AOT has recently developed a new deployment pipeline, moving away from the legacy OpenShift-based deployment approach. The new deployment system leverages Helm Charts and offers several advantages. 

Firstly, the new AOT deployment files are now hosted in a separate repository, which you can find at [this link](https://github.com/AOT-Technologies/forms-flow-ai-deployment).

Here are some key characteristics of our new deployment system:

1. **Helm Chart-Based**: The new deployment system is built on Helm Charts, which provide a standardized and modular approach to deploying applications. Helm Charts enable easier management, versioning, and sharing of application configurations.

2. **Flexibility Across Cloud Providers**: With the adoption of Helm Charts, our deployment can now run on various Kubernetes-compliant cloud providers, including AWS EKS, OpenShift, and more. This flexibility allows us to deploy our applications on the provider that best suits our specific needs.

3. **Easier Maintenance**: We have put effort into streamlining our deployment files. By leveraging Helm Charts and customizations, most of the deployment-specific tasks are handled through arguments passed to the charts. This approach simplifies maintenance, making it easier to update and manage our deployment configurations.

Please feel free to review the deployment repository for further details and specific instructions on deploying our applications.

**Comment by Abuchana** [comment]
Consult with AOT

**Comment by warrenchristian1telus** [comment]
A new repository has been created. Forked from AOT repo. It will be used to develop and deploy the new helm charts and integrate customizations. https://github.com/bcgov/forms-flow-ai-charts

**Comment by warrenchristian1telus** [comment]
We will need to justify our existing and request fro additional resources to Platform Services Team.

- These environments are sized to accommodate the required performance as determined utilizing load testing.
- We have found we need to “reserve” these levels to get the required load performance.
- These systems are not yet live but will be soon, which is why there is low utilization. Once live, utilization will increase.
- If there are configuration changes that anyone can suggest that will allow us to “reserve” less and still get the required performance, we would be willing to work on validation of those proposals.

Reports from AOT suggest that the new version has redundant databases by default, which means adding extra pods and resources for that. Also, Camunda/BPM can handle roughly 10 concurrent submissions per server, so 5 = 50 concurrent submissions, which I think would be bare minimum for our use case. We may need even more when things get busy.

**Comment by fazil-ey** [comment]
We have the plan on how to implement this. Implementation is part of #1246. The resourcing issues can be handled after the implementation
