### ISSUE TITLE
Telework Update relaunch - July 14

### ISSUE THREAD

**Issue by Andrew-Vargas-bcgov** [bcgov/digital-journeys#1238]
Launch updated telework form on Friday, July 14th. 

- Move changes to prod
- Test form updates to ensure functionality

If we need to deploy any code changes, please feel free to update this ticket.
@ccoldwell can you add the features/changes that need to be tested in this ticket?

**Comment by chriscaldwell-psa** [comment]
I’ll need to remove the #ccoldwell - from Zenhub  since I”m caldwell.  :)

On Jul 7, 2023, at 1:12 PM, Andrew Vargas ***@***.***> wrote:



Launch updated telework form on Friday, July 14th.

  *   Move changes to prod
  *   Test form updates to ensure functionality

If we need to deploy any code changes, please feel free to update this ticket.
@ccoldwell<https://github.com/ccoldwell> can you add the features/changes that need to be tested in this ticket?
