### ISSUE TITLE
Mat/Pat - Supervisor Process Takes too long -  Error Handling

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1425]
Context
- Handle the cases when the approval takes to long and we see the loading icon 
- There is an issue with the Camunda to CRM connection that produces a timeout error. This needs to be investigated and proper steps taken to fix it and if CRM call fails has proper messaging to user and form status should reflect that.
- Connection timeout should be reasonable. Currently, it is 5 mins. this is too long to expect the user to wait. Reasonable time - 60  seconds 

**AC**
- [ ] Fix the issues causing the process to go to loading endlessly OR show an error message with the action on what the applicant needs to do to successfully submit after a reasonable amount of time
- [ ] The status should not be "APPROVED" if the CRM ticket is not created. It should be "NEW" if the CRM ticket is not created.

**Comment by MeghanStothers** [comment]
Discussed with Bhumin - potential issue around the token.

**Comment by MeghanStothers** [comment]
Only happens on dev and test

**Comment by iman-jamali-fw** [comment]
### Camunda-CRM Connection Timeout Issue Findings:

- Isolated calls to CRM are all going well, indicating that this shouldn't be an issue from the CRM end.
- Using the `crul` utility that was added to the Camunda pod on Openshift (on TEST/DEV), a Bash script was run on the Camunda pod's terminal, calling CRM at short intervals. Thousands of calls were all successful, indicating that the issue shouldn't be at the Openshift/pod level.
- Mat/Pat workflow was edited to make the CRM call step asynchronous and reverted, but neither has helped the issue go away.
- The BPM auth token error previously suspected to have something to do with this issue was never seen in the logs during the tests and investigation. Most probably, this has nothing to do with the BPM/API token error randomly logged in the Camunda terminal.

**Comment by iman-jamali-fw** [comment]
Changing the http library that was used to call CRM related endpionts in Camunda was finally fixed the problem.
All the CRM related calls (create/update) should work with no issue. No timeout error logs was seen since the fix was deployed to DEV and TEST.

Also, CRM calls now capture errors (4xx/5xx) and in case of an issue, it should be recorded as incident in Camunda. Additionally the connection timeout limit in Camunda was reduced from 5 mins to 1 min and 30 seconds.

There was one submission that failed due to an issue with formio token that was used in Camunda which was discussed with Simen and all the findings regarding that issue was documented in ticket [#1446](https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/gh/bcgov/digital-journeys/1446).

**Comment by iman-jamali-fw** [comment]
@ayushdamani @fazil-ey 
This is ready for testing on TEST. For testing please submit Mat/pat approval/reapproval as supervisor and expect to see all submissions go through. If you see the process takes too long (it should throw an error after 1 min and 30 seconds), flag it and let me know. Good luck with testing :)

**Comment by iman-jamali-fw** [comment]
@fazil-ey 
Regarding the second AC: _**The status should not be "APPROVED" if the CRM ticket is not created. It should be "NEW" if the CRM ticket is not created.**_
It is partially done. In other words, the cause of error that broke the CRM step in the workflow is resolve and in case of an error, Camunda would capture and report it as an incident, giving us a heads-up and a way to recover the failure. However, the status, still, will be `approved` in case of an issue in CRM step in the workflow. If you think we need to improve this part for MVP, I'd suggest creating a separate ticket and do it after mat/pat workflow simplified (#1306).

**Comment by MeghanStothers** [comment]
ready for testing - see comments for how to test

**Comment by Stella-Archer** [comment]
supervisor approval now takes about 15sec we need top have have a loader message, see ticket #1427

**Comment by Stella-Archer** [comment]
error when I go back and change a date as supervisor this is recorded in #1451

**Comment by Stella-Archer** [comment]
PO Approved, message needs to be added to #1427
