### ISSUE TITLE
Mat/Pat -  Content change on allowance pages (from legal review)

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1516]
- [ ] Change the deferral option on on both maternity allowance page to - 

> I want to defer my decision to claim maternity leave allowance. I can choose to claim my allowance after I return to work up to the date i complete my return to work requirements. I also understand that I will have to provide proof of acceptance from EI to BC Public Service to claim allowance

- [ ] Change the deferral option on on both parental allowance page to - 

> I want to defer my decision to claim parental leave allowance. I can choose to claim my allowance after I return to work up to the date i complete my return to work requirements. I also understand that I will have to provide proof of acceptance from EI to BC Public Service to claim allowance

- [ ] Remove "When I did decide to return to work, the process of claiming allowance was straightforward and hassle free" from the story in maternity allowance leave

**Comment by MeghanStothers** [comment]
Mike to make these updates in dev and test and then to forward to Bhumin to forward

**Comment by Stella-Archer** [comment]
<img width="525" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0Z0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6805ced6669730d71a89a9c48a825adb31c1d0c/image.png" alt="image.png" />
Before you Begin:

I reco
mmend adding the following to the “Before you Begin” bullet as highlighted below:
•	Policy information in this form was last updated on December 20, 2023. Leave policy can occasionally change because of changes in the Employment Standards Act, collective agreements or employment insurance policy. The form is updated regularly, however, we recommend you review the latest information in your collective agreement and on the Maternity and Parental employment insurance benefits page and Careers & MyHR

Allowances

I noticed the wording when you’re going through the form doesn’t match the wording on the summary page.  Can we update this in both the maternity and parental allowance pages and the summary.

Can we please update to say:  

•	I want to defer my decision to claim maternity/parental allowance.  I can choose to claim my allowance once I return to work up to the date I complete my return to work requirements.

 

 
 
 

Examples

Amanda said for the examples…she doesn’t see anything problematic, but we do have the risk of employees attempting to use the examples as justifying what they did and then blaming it if something goes wrong.  She said that we should stay as objective as possible.  For example – we should remove the highlighted.  What if they don’t have that experience and we’re telling them that it’s straightforward and hassle free?

"I was not sure if I would be returning to work. Since my partner's parental leave allowance gave me enough buffer financially to take the time to decide, I chose to defer and claimed my allowance after I returned to work. I had peace of mind during the leave and no undue pressure of having to return money if I decided not to come back to work. When I did decide to return to work, the process of claiming allowance was straightforward and hassle free."

**Comment by MikePSA** [comment]
Content changes have been made in both dev and test environments, please review.

**Comment by Stella-Archer** [comment]
1/ Before you begin looks great, links have ben tested as well
<img width="1783" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTF1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--256a83b7716a96039095999657853bb5bd7e30f1/image.png" alt="image.png" />

2/ Allowance look complete and accurate in all places
<img width="1815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXh1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdcdf728df5e61a53f469a393f78eb22ae3538de/image.png" alt="image.png" />
