### ISSUE TITLE
Mat/pat - Minor corrections in error messages

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1552]
- [x] In Parental leave allowance dates that the error message if someone takes more than 35 weeks of standard allowance has a missing "weeks" in the end - "One parent cannot claim standard allowance for more than 35". 

It should say "One parent cannot claim standard allowance for more than 35 weeks". 

- [x] For maternity leave, if start date is in the past it does not show the correct error message. It should say "You cannot select a date in the past for the start of your parental leave"
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0REQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7bf1b409b5ea205a9f47de3e162eb6b2f84802aa/Screenshot%202024-01-12%20at%209.51.53%20PM.png" alt="Screenshot 2024-01-12 at 9.51.53 PM.png" />

- [ ] For Parental leave, there is an extra *. It should just say  "You cannot select a date in the past for the start of your parental leave"
<img width="1268" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0xEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2a99d5e51a179bf5425619b4818cd8689fcd808/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
@fazil-ey 
"You cannot select a date in the past for the start of your _parental leave_"
Is it correct validation error for maternity leave start date in past?

**Comment by Andrew-Vargas-bcgov** [comment]
Fixed the validation issues.


@fazil-ey  For the parental leave validation. Since there are so many possible and overlapping errors, Iman and I thought that we should display multiple messages with the asterisk as the separator. The platform does not allow us to show multiple errors in a better way, so it is more a limitation if we want to show it like this. It would be possible to only show one error at a time, but it might be annoying for the user to keep cycling through issues until a date works.

**Comment by fazil-ey** [comment]
@Andrew-Vargas-bcgov  we can leave it as is with the asterix!

**Comment by ayushdamani** [comment]
Updated, thanks Andrew!

**Comment by fazil-ey** [comment]
both error messages are correct now. We can ignore AC 3

**Comment by MikePSA** [comment]
Tested in PROD, looks good. Closing.
