### ISSUE TITLE
TELEWORK: Dates/Time-zone issue: The user is displayed with the wrong dates than what was entered

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#163]
**Background:** The user is displayed with the wrong dates than what was entered.

**Steps to Reproduce:**

1. Log in to the PSA-Digital-Journey portal on dev as a non-admin user with valid credentials.
2. Click on “Submit New” on the telework form.
3. Enter the Telework schedule date implemented on as today's date: 3/24
4. Enter the Date signed as today's date: 3/24
![Screen Shot 2022-03-24 at 4.25.01 PM.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/1566d89c-e747-4232-8e97-1e275cc82fef)
5. Fill in all the required fields.
6. Click on “Submit”.
7. As a supervisor, check your e-mail and click on the submitted application's link to review it.
8. The dates are showing as past date 3/23, and the supervisor is unable to submit his decision. 
[Reference Application](https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form/61e9f5286dd5b367312d9c2e/submission/623cb374b6fef0bf7ed34729)
![image (2).png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/f36e2f60-f708-4df1-876a-b2a4a0fdd2fd)

**Actual Behavior:** The user is displayed with the wrong dates than what was entered.

**Expected Behavior:** The dates should remain as entered, and the supervisor should be able to submit his decision. 

**Environment :** dev

**Comment by qudsia-khan-fw** [comment]
Still showing as yesterday's date

**Comment by iman-jamali-fw** [comment]
The issue is rooted in displaying dates in the viewer's time zone. If submitter and viewer/supervisor timezones are different, then dates might be one day off when viewed by the supervisor. 

The standard solution is through the form builder, in the `Display in Timezone` option as shown in the attached image. Unfortunately, this feature is not working as expected at the moment. It's a bug in Formio which is reported [here.](https://github.com/formio/formio.js/issues/4549).


![Screen Shot 2022-03-29 at 3.15.37 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/5c6f2bae-5f4f-4aa5-8c01-6ebb0b7ad1f7)

![Screen Shot 2022-03-29 at 3.19.57 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/a05786f0-4ef3-4823-85e7-d703cab927af)

**Comment by MeghanStothers** [comment]
closed after group review Aug 10
