### ISSUE TITLE
BUG: Recommended link(s) Careers & MyHR

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#1783]
As an employee searching for the digital Mat/Pat form on Careers & MyHR, I'd like one easy-to-access link to the digital form:
<img width="1131" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0RwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55809c571c44152d007e6a5942256af29a3b165d/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment]
I've tweaked it to return on 'exact match' rather than Phrase
<img width="1005" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGNVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b7a4dc883636c06f255289566b3a53ace86e444/image.png" alt="image.png" />

<img width="1177" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGdVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--568ed98957b323b90c2f840b7e3c45c9c242bdc2/image.png" alt="image.png" />


<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGtVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6763e077a3132453520cdc471c736e915ec0fe00/image.png" alt="image.png" />

**Comment by fazil-ey** [comment]
<img width="1374" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNElaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb3c26a9ece15e74e783f69959995909f8ee9501/image.png" alt="image.png" />
<img width="1364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE1aQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebe8298cb47b79718377a2425f9023089ecf1ee6/image.png" alt="image.png" />


both look good
