### ISSUE TITLE
[Mat/Par]: checkbox submission issue

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1853]
**User Story**
A short, simple description of a feature or issue told from the perspective of the user.
“As a <user role> I want <this action> so I can get <this value>.” 

**Tasks**
Steps needed to achieve this feature. 

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [ ] End-to-end functional testing 
- [ ] End-to-end UX testing
- [ ] If change is data impacting, test to confirm data has been sent with BI/DIO team

**Comment by bhumin-fw** [comment]
In the investigation, we found that task assignment failed because one of the form component keys was more than 255 characters. This issue has been fixed, and the changes have been deployed to all environments. Additionally, we have updated two drafts that contained the same key details in the production database.
