### ISSUE TITLE
COI: Unable to open form review and process

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1855]
Form submitted with bcldb email employee and gov.bc.ca as supervisor is not accessible in the Review & Process tab. It is seen in the list but it is frozen/blocked with a overlay on it. 

<img width="1755" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2ZTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce2a3b3c754e9241b3b4fd7924fc39e1fb9831ba/image.png" alt="image.png" />

**Comment by bhumin-fw** [comment]
@fazil-ey The file is assigned to <email>_ldb if the email is from bcldb.com. That's why it does not allow you to open it, as your username is <email>_idir.

I can copy file attachments to the initial email that the user receives after form submission. Alternatively, I can assign a static value for user assignment so you can see those attachments in the digital journey's email after approval.

**Comment by fazil-ey** [comment]
I think we are good. We know ldb employees will have lbd supervisors. 

Best approach is to directly test with LDB folks. We can close this ticket
