### ISSUE TITLE
[Tool]: Coding dates into Mat/Par Selenium Test

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#1884]
**User Story**
“As a Selenium test builder, I want a efficient way to record dates of leaves so they sync up accurately not matter when I run the tests so I can get accurate results from testing and not hand fix tests every time we need to deploy.” 

**Tasks**
Steps needed to achieve this feature. 

**Acceptance Criteria**
The checklist the product owner uses to decide whether a story is done. Objective and discrete answers (such as a yes/no) that can be tested.
- [ ] End-to-end functional testing 
- [ ] End-to-end UX testing
- [ ] If change is data impacting, test to confirm data has been sent with BI/DIO team

**Comment by MikePSA** [comment]
Try these two execute script commands and it should solve this problem. To change the amount of days, you need to change the number "+ 3" in first line.
 
**First line** 

- Command: execute script
- Target: var date = new Date(); date.setDate(date.getDate() + 3); return date.toISOString().split('T')[0];
- Value: futureDate

**Second line**

- Command: execute script
- Target: document.evaluate("/html/body/div[1]/div/div[2]/div/div/div[2]/div/div/div[3]/div/div/div/div/div/div[5]/div[1]/div[1]/div[1]/div/input[2]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.value = ${futureDate};
- Value: (empty)

<img width="1167" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--774bff7a9b41740519d8ed705438284887c0d38f/image.png" alt="image.png" />

After you need to record a click on the date field and any blank space on the page just so the form registers the input in the date field so you can click the next button without validation errors, otherwise it won't let you.

**Comment by Andrew-Vargas-bcgov** [comment]
going to write some documentation for the teams channel selenium testing folder
