### ISSUE TITLE
Telework launch plan

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#432]
As a dev team launching the Telework agreement to all employees on August 2, we want a coordinated plan to ensure a successful launch. 

The a/c will include:

A current reference with daily tasks, assigned roles and times 

SEE LATEST PLAN BELOW

**Comment by MeghanStothers** [comment]
LAUNCH PLAN - Updated Wednesday July 27 at noon

**WEDNESDAY**

- 2:30: Simen to push all work to prod (Simen to advise Stella when this work is complete)
- Stella's team (Don, Hasan, Alex, Stella) to test prod environment and identify bugs, write/update tickets
- Meghan/Stella to prioritize work/tickets


****THURSDAY****
- (ALL) 8:45 a.m. scrum - highlight priority work for dev team, identify barriers
- (SIMEN) 2 p.m. push to prod
- (WARREN/SIMEN) After 2 p.m. Clean out earlier submissions from prod (2 databases and Kamunda) - Advise Stella when this has been completed
- (Stella's team) Testing after 2 p.m. 


**FRIDAY**
- Non-PSA DEVS not available
- Stella's team to review of prod/updates tickets

**TUESDAY**
8:45 a.m. scrum - any priority fixes identified 
9 to 11 a.m. Scrum team tackle fixes
9 to 11  Stella's team + PSA writers/comms test form
11 a.m. Link made live in Careers & MyHR content where form will be accessed by employees

**Comment by MeghanStothers** [comment]
Nice work! @simensma-fresh @iman-jamali-fw are you/team still okay to push last bits to prod at 2 p.m. today?

**Comment by simensma-fresh** [comment]
@MeghanStothers We just pushed the latest changes to prod!

**Comment by DonMoffatt** [comment]
Hi @simensma-fresh Will the email address validation scripts be added in soon?

**Comment by simensma-fresh** [comment]
Hi Don,
I’m just out for a little bit. Feel free to copy the validation scripts over from dev. We have not made any other modifications to the forms.

From: DonMoffatt ***@***.***>
Date: Thursday, July 28, 2022 at 2:20 PM
To: bcgov/digital-journeys ***@***.***>
Cc: Simen Smaaberg ***@***.***>, Mention ***@***.***>
Subject: Re: [bcgov/digital-journeys] Telework launch plan (Issue #432)

Hi @simensma-fresh<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsimensma-fresh&data=05%7C01%7CSimen.Smaaberg%40ca.ey.com%7C266eb1b6894d40279a4508da70deef32%7C5b973f9977df4bebb27daa0c70b8482c%7C0%7C0%7C637946400067825977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JjpmzODaNtZuPVfLJzAk%2FE9aRZHsDhMXaNjXuUG%2F06o%3D&reserved=0> Will the email address validation scripts be added in soon?

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbcgov%2Fdigital-journeys%2Fissues%2F432%23issuecomment-1198641562&data=05%7C01%7CSimen.Smaaberg%40ca.ey.com%7C266eb1b6894d40279a4508da70deef32%7C5b973f9977df4bebb27daa0c70b8482c%7C0%7C0%7C637946400067825977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lonFQPejZ3h3Qs%2BeV7Jgi%2FTQgrRM1pdd%2Fpa3EXPkGPI%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAP4MK3SG3ATSY4CWCIBHQ2DVWL2PXANCNFSM54A5HMYQ&data=05%7C01%7CSimen.Smaaberg%40ca.ey.com%7C266eb1b6894d40279a4508da70deef32%7C5b973f9977df4bebb27daa0c70b8482c%7C0%7C0%7C637946400067825977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bzPolOq%2FFGwmTBWD%2FnxMUTHugpW28HbIuw1JIwnvRl8%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


CONFIDENTIAL and/or PRIVILEGED. If received in error please notify the sender and permanently delete. CONFIDENTIEL et/ou PRIVILÉGIÉ. Si ce courriel est reçu par erreur, veuillez nous en aviser et en effacer toute trace. EY, 100 Adelaide Street West, PO Box 1 Toronto, ON M5H 0B3. www.ey.com/ca To unsubscribe from commercial electronic messages / Pour vous désabonner des messages électroniques commerciaux : ***@***.***

**Comment by DonMoffatt** [comment]
@simensma-fresh I've added the validation in PROD.

**Comment by DonMoffatt** [comment]
Hi Simen,

Does this code need to be in both the employee email and manager email box?

if (input) {
  valid = data.email?.toLowerCase() !== input?.toLowerCase() ? true : 'Employee and manager cannot have the same email';
}

Don

**Comment by simensma-fresh** [comment]
Yup! It will be in both places. I just verified the logic in prod and should be working correctly now

From: DonMoffatt ***@***.***>
Date: Thursday, July 28, 2022 at 2:45 PM
To: bcgov/digital-journeys ***@***.***>
Cc: Simen Smaaberg ***@***.***>, Mention ***@***.***>
Subject: Re: [bcgov/digital-journeys] Telework launch plan (Issue #432)
Hi Simen,

Does this code need to be in both the employee email and manager email box?

if (input) {
valid = data.email?.toLowerCase() !== input?.toLowerCase() ? true : 'Employee and manager cannot have the same email';
}

Don

**Comment by DonMoffatt** [comment]
Thanks - we tested the validation and it works.

**Comment by DonMoffatt** [comment]
@simensma-fresh @iman-jamali-fw As noted in an email sent just now, we are having a problem with the workflow becoming disconnected from the form in PROD.

**Comment by DonMoffatt** [comment]
> @simensma-fresh @iman-jamali-fw As noted in an email sent just now, we are having a problem with the workflow becoming disconnected from the form in PROD.

@simensma-fresh notified me by email that he was able to reconnect it using a workaround and will fix the bug next week. For now, we are good to go for launch and our team will stay out of the form.

**Comment by MeghanStothers** [comment]
@simensma-fresh @warrenchristian1telus Will you be able to clean our earlier submissions today?

**Comment by simensma-fresh** [comment]
@MeghanStothers I've just been working with @warrenchristian1telus to debug some issues with the load test in prod - which will carry on into tomorrow. I would suggest that I remove the old submissions Monday night to make sure any further submissions get cleaned out as well

**Comment by MeghanStothers** [comment]
@Simen yes! I am grateful you turned your efforts to the debugging issues. Thank you. The old submissions can be removed on Monday night (or Tuesday morning if it doesn't take a long to do - your call a we have some flexibility with the 11 a.m. launch time. Let us know an approximate time we can start testing tomorrow so we don't interfere with anything and see the latest.

**Comment by MeghanStothers** [comment]
Simen reports that all previous submissions have ben cleaned out from prod and he will do test and dev.

**Comment by MeghanStothers** [comment]
Our Telework form invitation is now live on Compass: https://compass.gww.gov.bc.ca/the-telework-agreement-goes-digital/

So many hands and hearts (end editorial eyes and enthusiasm) went into this collaboration.  The devs are amazing!


My deep thanks for your parts in our success. We’ll have a debrief as soon as tomorrow afternoon, and we’ll watch our new digital journeys inbox for feedback.   

Thank you! Thank you!

**Comment by MeghanStothers** [comment]
Issue #1 ministry name change - manually added, tested by Don and Hasan. Longer-term solution needed to keep ministry names current in the tool.
Issue #2 date field blank in pdf copy of agreement - Simen did a quick workaround to lock-in the current date and we'll look for a longer term fix. Workflow updated.

Thanks all!

**Comment by warrenchristian1telus** [comment]
Hi @MeghanStothers - I would think that this could be pulled from HR data regularly, to automate the process. I'm not sure, but it looks to me like [api.rsc/Datamart_BCIB_PeopleSoft_PS_BUS_UNIT_TBL_HR/](https://analytics-api.psa.gov.bc.ca/apiserver/api.rsc/Datamart_BCIB_PeopleSoft_PS_BUS_UNIT_TBL_HR/) may be a good candidate.

Maybe @simensma-fresh or @iman-jamali-fw could comment more on what it would take to do on our end.

We may need separate credentials to access that endpoint (BCIB vs. Telework). Or it may be better / easier to get a copy of anything we need in the Datamart_Telework namespace (such as Datamart_Telework_PeopleSoft_BUS_UNIT).

**Comment by simensma-fresh** [comment]
It would indeed be possible to pull this from the ODS if such endpoints exist. The Form builder does support fetching dropdown options dynamically, so with and endpoint added to our API to proxy the call through (for auth) this should work fine.

A reusable "ministry selection" dropdown would also be possible to add to the Form Builder in case a similar dropdown will be needed in future forms.
