### ISSUE TITLE
Validation Error is not visible to manager submitting

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#468]
Background: As a manager I am trying to submit my decision on a telework agreement. I don't notice or see the 'agree' button. 
Nothing appears to happen when I submit as the validation error is happening in an area I can't see on the screen
 
Steps to Reproduce: process a telework form for more than 3 days, manager does NOT select 'agree' but does everything else correctly, then submits... it look like it's broken and nothing happened
 
Actual Behavior: Manager does not see the validation error on the area of the screen where they are working
 
Expected Behaviour: Manager should see the validation error on the area of the screen where they are working
 
Environment: ALL![Validation Message is not on submit screen.gif](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/ca6e335b-ee39-48ce-a0a0-7fea4c652463)

**Comment by Stella-Archer** [comment]
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/de53b6b8-fb17-4203-bac0-d653b8ed4d78)

**Comment by simensma-fresh** [comment]
Would a solution where we scroll you to where the error message is be OK here? 

@david-sabadash If so, There might be some built in functionality we can use for this: https://github.com/formio/formio.js/issues/3650

**Comment by david-sabadash** [comment]
Investigation ccomplete on this task; currently the component we need access to in order to implement this functionality is not exposed to us in our implementation. None of the currently available properties of the Form component accurately allow us to catch validation events and focus them on the screen. In order to implement this functionality, a full reimplementation of the Form component would be needed. This is related to @simensma-fresh 's suggestion - the class method mentioned in the formio repo is only accessible in the core JS library, and not in the react-formio library we currently have implemented. we would need to switch over to the formio.js library, or alternatively, make a local override for the Form component similar to how we are handling the existing forms-flow-ai component overrides.

**Comment by MeghanStothers** [comment]
Decision to keep it open at today sprint review - Simen might have a workaround and will connect with David.

Another option is a pop-up message
Another option is the red box at top of page that lists errors.

**Comment by HasanSifat** [comment]
Tested successfully in DEV. Ready to be transferred to TEST

**Comment by Stella-Archer** [comment]
yay this w![PushedUptoMessage.gif](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/608f65f6-fb62-4725-b093-f109f5724d9e)orked great in DEV move it over please :)

**Comment by Abuchana** [comment]
Can be moved to Test

**Comment by iman-jamali-fw** [comment]
@Stella-Archer @HasanSifat  Ready to be tested on TEST

**Comment by HasanSifat** [comment]
Tested successfully in TEST- ![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/d569e8fe-5906-41c3-bc01-fa823b2b5c00)

Ready to be transferred to PROD

**Comment by Stella-Archer** [comment]
Yes, this is Good in TEST please move to PROD![SubmitValidationTEST.gif](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/4a168f77-8470-45aa-a4b7-0eacb573615b)

**Comment by HasanSifat** [comment]
tested successfully in PROD! Ready to be closed ![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/4c05d74a-2fc5-440d-a6e2-938ee4632253)
