### ISSUE TITLE
Update to formsflow.ai 4.0.6

### ISSUE THREAD

**Issue by Abuchana** [bcgov/digital-journeys#488]
**Description** 
The Digitial Journeys project is currently running on formsflow v4.0.4. A need for features in the latest formsflow version has been identified, so a version upgrade is needed.

**Acceptance Criteria**
- Our repo is updated to be based on formsflow v4.0.6
- Telework form AND workflow is tested to be working as before the upgrade.

**Comment by simensma-fresh** [comment]
Approach for getting this upgrade done has been discussed with @iman-jamali-fw and @david-sabadash. We have a path forward that should make such upgrades easier in the future, and improve our development processes

**Comment by Abuchana** [comment]
@simensma-fresh, do you have a ballpark ETA for completion? Are we looking at a few days, weeks...?

**Comment by simensma-fresh** [comment]
@Abuchana We put it at a 13 as it's got some risks associated with it. I think a few days would be a reasonable guess here for the majority of the work, with the potential for some fixes needed after testing out the solution in dev. 

@david-sabadash Is taking the lead on this one, the rest of the team should be able to continue work in parallel

**Comment by Abuchana** [comment]
@simensma-fresh, sounds good, thank you!

**Comment by HasanSifat** [comment]
Further updates coming Tuesday

**Comment by HasanSifat** [comment]
Tentative time for testing is late Thursday or early friday

**Comment by MeghanStothers** [comment]
David to work with Simen on update planning. Testing to begin early next week.
David has a version of earlier version saved.

**Comment by DonMoffatt** [comment]
Results from testing in the DEV environment today:
-  signature date field appears empty in PDFs sent to employee and supervisor. This is true later in the process as well (final copies). It is true for Occassional, <3 days, and 3+ day cases. 
- implementation date field is empty inside the tool when manager's are reviewing an application.

**Comment by david-sabadash** [comment]
**Results from general testing**

UI Bugs: 

- View/Edit form buttons are partially cut off
![Screenshot 2022-08-16 231003.png](https://images.zenhubusercontent.com/62b33d00d955ad0dc2151a98/395e6f5e-3bad-4151-bdd9-481e121f6def)

- Applications page text wrapping bug
![Screenshot 2022-08-16 232552.png](https://images.zenhubusercontent.com/62b33d00d955ad0dc2151a98/80e2f94a-485e-4e63-bedd-e6d7d63e6f38)

Functional Changes:

- Task filter bar functionality seems to have changed. This isn't so much a 'bug', rather it needs a decision on whether or not the new version is acceptable (NEEDS CONFIRMATION) 
![Screenshot 2022-08-16 232448.png](https://images.zenhubusercontent.com/62b33d00d955ad0dc2151a98/97f6f28f-25a6-4bea-94e0-510d01c88fde)

non-repeatable bugs:

-  Under certain circumstances, a full-page iFrame gets inserted into the DOM on the /form page. This iFrame blocks all user input, including signing out. The DOM lists it as a separate 'document' being injected into the page with the element tag '#document', complete with it's own body element. This iFrame seems to originate from a component that is checking roles, however I can't confirm that 100%. The bug does not occur every time, and I have not been able to get a screenshot of it in action.

- Under certain circumstances, I've observed the navigation tab options getting duplicated. There ends up being two sets of 'Admin | Review and Process Applications |` tabs, with the second set being inserted underneath the first, causing the navbar to become unusually tall. I haven't been able to locate the cause of the bug, or to get it to happen reliably, however the first time it happened occurred when changing the overall window size, so that may be related.

**Comment by Abuchana** [comment]
@simensma-fresh can you confirm this has been pushed to Prod?

**Comment by MeghanStothers** [comment]
Has been pushed to prod
