### ISSUE TITLE
TELEWORK: Incomplete submissions available to managers review even after 1 month of submission

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#558]
Background: Managers have sent messages to the mailbox that they have submissions to review in the task tab that after submitting a decision, the task does not go away. Upon further investigation, it was identified that these submissions were more than a month old
 
Steps to Reproduce: not too sure how to reproduce this in prod
 
Actual Behavior: incomplete submissions for review to managers are still in the task tab after more than a month of submission.  
 
Expected Behaviour: all incomplete submissions should be deleted and not available for review after a month. 
 
Environment: PROD

**Comment by iman-jamali-fw** [comment]
**The issue**
There are a number of incompleted submissions in PROD that are older than 30 days old but have not been removed.

**Result of testing two scenarios**

I tested to see if deploying a new Camunda model cancels the timer that triggers the removal of incomplete submissions. My result shows that it **won't cancel the timer and removal works as expected**.

I also tested to see if stopping/starting the Camunda container would affect the timer. It turns out **it doesn't and submissions will be deleted on time**, or in case of time has elapsed, the submissions will be deleted as the Camunda container up again.



**Side effect of the new draft feature on deleting submissions (called application in webApi)**
In v5, in case an application was completed from a draft, deleting that application will fail in webApi since a draft references that application. To fix this issue, the draft of that application should be removed first.

**Comment by MeghanStothers** [comment]
@Stella-Archer @HasanSifat let's re-test this one after the upgrade when we change the expiry date to 60 days

**Comment by fazil-ey** [comment]
Check this on Jan 8, 2023. There are forms in production that were submitted in November.

**Comment by Stella-Archer** [comment]
check PROD to see if there is anything older that 60 days still there

**Comment by iman-jamali-fw** [comment]
I looked into the incomplete submissions in PROD and found out that not all data was deleted for some users (about 33 of them). The submissions themselves got deleted, but the info about them (metadata) in the API's database didn't get deleted properly.

I tried it out myself and got the same issue on my computer, so now I'm trying to figure out what's causing it.

I was able to reproduce the issue on my local, so now I'm trying to figure out what's causing it.

**Comment by iman-jamali-fw** [comment]
I discovered that incomplete submissions scheduled for deletion on Jan 11th and 12th couldn't be located, causing errors and preventing the deletion of other data. To fix this, I updated the deletion process in Camunda to handle missing submissions. Now, if any piece of submission is already deleted, or cannot be found for any reason, the deletion process will continue smoothly without errors.

**Comment by iman-jamali-fw** [comment]
Deployed to DEV and TEST. Let you know for testing when deployed to PROD where the incidents exist and can be tested.

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 
The fix for the incidents in Camunda has been deployed to PROD and is now ready for testing. There were originally around 30 related incidents in Camunda, but after the fix was deployed, I retried those failed jobs and successfully finished and deleted the rest of the incomplete submissions. I have left three failed jobs for you to test.

**Please follow these testing instructions**
log in to the Camunda admin dashboard on PROD (https://digital-journeys-camunda.apps.silver.devops.gov.bc.ca/camunda/app/welcome/default/#!/welcome), navigate to the Telework process definition, select version 22, go to the incidents tab, and click the loop icon to retry those failed jobs. After doing so, please wait for about 10 seconds and then refresh the page. You should see that all incidents have been resolved.

Attached is a screenshot of the Camunda admin dashboard for reference:

![Screenshot 2023-03-28 at 6.16.19 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/f405d090-dac4-4e99-ade8-055330295a7a)

**Comment by Stella-Archer** [comment]
I don't think I have the right permissions to access that ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/7a61d2b1-0940-4996-9633-1becb94d6b9f)

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 

You should have Camunda admin permission. Let me know if that didn't work.

**Comment by iman-jamali-fw** [comment]
@Stella-Archer Please ping me when you want to test it and I can help you navigate. It should take less than 5 minutes :)

**Comment by MeghanStothers** [comment]
Stella to connect with Iman today

**Comment by Stella-Archer** [comment]
PO Approved and closed :) (at last)
