### ISSUE TITLE
Nov 08 Launch Plan: Upgrade, changes to tool and Telework changes  

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#637]
As a forms program area, product owners and senior leaders team and devs, we would like to make sure that we have wrapped all work and have launched the forms tool updates as planned and pushed all wok to prod, And tested!

- [x] PIA Changes to telework Confirmed

- [x] Release note to PROD. Copy to be provided soon!

**Comment by HasanSifat** [comment]
I had discussed this before, on Nov 15 (3 or days before) when we push v5.0.0 to PROD we can have a release note to feature on the front page. This release note can highlight the draft feature and the tabs avaialble now through the navigation bar. 

Also, the link for telework on myHR can now be directed to the forms tab instead of directly to the telework form.

**Comment by HasanSifat** [comment]
A release note similar to PDP to be displayed for users signing in for the first time after new release. 
![image.png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/95e64703-5585-4f6c-a7b9-434c34bde5cb)

**Comment by HasanSifat** [comment]
November 9th deadline to push to PROD

- solve telework MVP tickets 

- release note built

**Comment by MeghanStothers** [comment]
Decision made at scrum we will
1) Nov 8: Do the upgrade end of Day Tuesday Nov 8
2) Nov 9, 10: have two days to test, write tickets, etc. 
3) Nov 9: publish changes to the Careers & MyHR website
3) Nov 9: Advised Sean/PIE when the change have been made

**Comment by HasanSifat** [comment]
launch complete! All listed activities are complete. Closing ticket
