### ISSUE TITLE
TOOL: PDF branding

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#71]
As a Digital Journeys user I would like to have any PDF copy of forms be branded.

**A/C**
- The pdfs need to be branded at every stage of the form: 
1) The unfilled Telework form (this one ![MicrosoftTeams-image (6).png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/04758262-4619-4672-9d18-6b54bec4215b)![MicrosoftTeams-image (5).png](https://images.zenhubusercontent.com/61ddb02eac135d772cfce6ec/00419f3a-5737-4a75-9006-ce3588690dbf)
2) When the employee wants to preview or print a partially completed form (that is not yet been approved by manager)
3) as a completed form (pdf) that is emailed to the manager 
4) as a completed form (pdf) that is emailed to employee 

- Generated PDF's are branded according to the mock-up (to be provided)
- Only display the file name and disable links to files in the pdf because it gives "Unauthorized" upon click

**Notes:**
- Logo
- FOIP / footer
- Meghan to provide more details
- styling needed 

Attaching the form send with email which has the correct branding
[https://app.zenhub.com/files/439477060/7f172d2b-bde5-4d30-88dc-b6018a192305/download](https://app.zenhub.com/files/439477060/7f172d2b-bde5-4d30-88dc-b6018a192305/download)

**Comment by jchow11** [comment]
https://www.figma.com/file/gQDAaN0lnJJj1xg6NXFEsI/Wireframes?node-id=581%3A13242

**Comment by jchow11** [comment]
![Generated Form PDF.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/cbe48de3-29d6-4d97-8fcc-be227ea4219e)

**Comment by jchow11** [comment]
![Generated Form PDF.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/6758b233-0011-4618-9931-2d31683a68fe)

**Comment by jchow11** [comment]
### UPDATED AC FOR @jizhaogit 

As a Digital Journeys user I would like to have any PDF copy of forms be branded.

A/C

The pdfs need to be branded at every stage of the form:
before the form is filled out
When the employee wants to preview or print a partially completed form (that is not yet been approved by manager)
as a completed form (pdf) that is emailed to the manager
as a completed form (pdf) that is emailed to employee
Generated PDF's are branded according to the mock-up (to be provided)
Only display the file name and disable links to files in the pdf because it gives "Unauthorized" upon click

**Required components:**
Where We Work Logo - size (height = 70px)
Form title = BC Sans Regular 17pt/24pt, right aligned #000000
Footer text (Date + page numbers) = BC Sans regular 10pt #000000
Lines = 1pt #CFCFCF

*All forms must have a FOIPPA – should be included as a business requirement when creating the initial form. They will then be included when PDF is created.

**Comment by jchow11** [comment]
Wireframe for reference.

![Generated Form PDF.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/9a08c164-439a-41f8-8e6d-f4ff469719e6)

**Comment by jchow11** [comment]
WIW Logo

![wiwlogo.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/a6023167-030e-4ca6-a7ee-fb121219b80c)

**Comment by schuyt** [comment]
For the email PDF's, we put the form/submission values into [this](https://github.com/bcgov/digital-journeys/blob/main/forms-flow-bpm/src/main/resources/templates/form.html) template and render it as a PDF using Playwright.

The "Download" button, however, is rendering it in the browser as a list of Key/Value pairs using [this page](https://github.com/AOT-Technologies/forms-flow-ai/tree/master/forms-flow-web/forms-flow-util).

Could replicate that on the client side if we wanted for the "Download" button, using something like https://react-pdf.org/ on the Form component, which would render it similarly.

`<Form
            form={form}
            submission={submission}
          />`

**Comment by jizhaogit** [comment]
next step:
1. fit A4 paper scape
2. page break

**Comment by Abuchana** [comment]
@iman-jamali-fw @Stella-Archer @MeghanStothers 
Is there a way to have the break in a better spot so it's not cutting off the boxes?
![image.png](https://images.zenhubusercontent.com/6005ca03d883b372a058fe50/17a61fac-67ce-48b6-bf8e-b3e0d938ba3b)

**Comment by iman-jamali-fw** [comment]
@Abuchana 
An easy but manual way is to adjust the form at the form designer level (this should be done for each form) to leave the break spot empty to prevent cut-off. The good thing about this you won't need a developer, and a designer can easily achieve this. 

And there should be a dynamic way at the pdf generation logic level. So far I did not find an easy way and think this should be hard to implement since PDF generation is a premium (paid) feature of Form.io. I can look into this if you decided to move forward this way.

**Comment by DonMoffatt** [comment]
@iman-jamali-fw This had been moved to QA but the branding / text break fixes changes have not been done. Was it there by mistake and it was actually still in progress? I have moved it to "In Progress" but please reassign it to the appropropriate pipe if that is not the best.

**Comment by Stella-Archer** [comment]
We are still having the horizontal cut off issue in all environments ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/0244c4eb-bebd-4822-9cf2-cf0084ae1080)

**Comment by DonMoffatt** [comment]
> We are still having the horizontal cut off issue in all environments ![image.png](https://camo.githubusercontent.com/7ca76f79fcb48fede2ce2c094fb4ca7c0f7f79c84ee5105e900c4897071c6b46/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631653561623461396135613165346264323761393262382f30323434633465622d626562642d343832322d396366322d636630303834616531303830)

@iman-jamali-fw 
Note that the text is cut off on the right margin in addition to the text break between pages that I mentioned.

**Comment by iman-jamali-fw** [comment]
Sorry, it was in pr review. The changes are not deployed yet. Will move it to Review once deployed.

**Comment by iman-jamali-fw** [comment]
@Stella-Archer @DonMoffatt The pdf generation is deployed and ready for test on DEV.

**Comment by HasanSifat** [comment]
tested out "print as pdf" button for unfilled or partially filled forms. The generated pdf is too enlarged to fit into a standard page for printing, as shown in the screenshots below-
 ![MicrosoftTeams-image (6).png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/83073064-0342-4f5c-92d2-874296a0b94c)
![MicrosoftTeams-image (5).png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/e174c904-f071-435e-a6b6-c12460834c42)

Vertical alignment of page break is still present. The possibility of shifting content around from the front end of the from through forms designer will not work. This is because there would be a significant gap in the content on the online version of the form. 

Would recommend to take this back into "In Progress" pipeline.

**Comment by HasanSifat** [comment]
Received updates on generated pdfs with slightly adjusted measurements so that the generated pdf is more printer-friendly. Waiting to go into the office tomorrow to make a printout of 2 possible sizes. 

Looking good to close this ticket after a final confirmation tomorrow. Yaay! Feels good to see this close to completion

**Comment by MeghanStothers** [comment]
Thanks @HasanSifat ! Let's preview this with @Stella-Archer tomorrow so we can see how this is working and what needs to be done

**Comment by iman-jamali-fw** [comment]
For the issue of page break, I'd see two options:

1. Have a generic function to export the pdf with no regard for page breaks. (easy to implement, reusable for other forms out-of-the-box)
2. Have a customized pdf generation for each form that makes sure page breaks are not breaking any form elements. This would require some dev efforts to move certain sections of the form (during the pdf generation) to fit on the pages. Such a solution would require some dev efforts per form (not 100% reusable).
3. Have a form designer to change the online form (with some margin) to

**Comment by warrenchristian1telus** [comment]
@iman-jamali-fw @HasanSifat I would like to suggest using HTML / CSS to print the form using "@media print" rules to ensure a clean print (no menus, etc.).

This would allow the computer / printer to handle page breaks, and I believe it would resolve a lot of challenges that come with PDF generation and printing.

It would also allow for more flexible print options, which I think would improve accessibility - larger fonts, different page sizes, etc.

This option may also be viable for emails with HTML templates, if we decide to go this route.

**Comment by HasanSifat** [comment]
I have received an updated attachment from @iman-jamali-fw with margins added at the top and bottom of the generated pdf. The content is still breaking apart at the margins. However, it is now less likely for content to be not printed at the bottom and end of a certain page. 
Updated pdf attached- [https://app.zenhub.com/files/439477060/34de4c76-a1a8-4f6c-a1d1-8fbd6596617c/download](https://app.zenhub.com/files/439477060/34de4c76-a1a8-4f6c-a1d1-8fbd6596617c/download)

**Comment by HasanSifat** [comment]
Good catch, there are two instances of this. The other one is in the 2nd-page calendar date field. @iman-jamali-fw mentioned this today that the application generating the pdf does not have the calendar icon in its repository and hence it is replacing these unknown icons with this "ds" icon. 

Is there a way to manually add the icon to the field to formsflow or the application generating the pdf?

**Comment by warrenchristian1telus** [comment]
@HasanSifat @iman-jamali-fw I think the FontAwesome (or any other fonts) can be added to the PDF as a resource. In the case of jspdf, something like this:

doc.addFont('/fonts/awesome/fontawesome-webfont.ttf', 'FontAwesome', 'normal', 'StandardEncoding');
doc.setFont('FontAwesome');

**Comment by HasanSifat** [comment]
According to our stand-up on Friday, there are 3 requirements put forth for this feature and after resolving them we can look into closing this issue. The 3 action items according to priority are as follows-  
1. Resolve the spacing of words in the form so that all content is left-justified 
2. Update missing icons in the generated pdf within formsflow.ai
3. Update the font used in the generated pdf to be BC Sans- https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/bc-sans

**Comment by iman-jamali-fw** [comment]
I spent some time on Friday and over the weekend and explored different pdf generation (client-side) solutions. Here are my findings along with an example of generated pdf for Telework form under each option.

1. With the current implementation with `jsPdf` the best thing I could do was to add the BCSans font. There are still issues with page breaks and icons not loading. BCSans font also has some problems.
[https://app.zenhub.com/files/439477060/4deed486-1ddb-4bd9-b20b-6a1d0de49c94/download](https://app.zenhub.com/files/439477060/4deed486-1ddb-4bd9-b20b-6a1d0de49c94/download)

2. Per Karim's suggestion, I tried to look into AOT, and find a pdf service in their codebase. However, it's pretty basic and does not include the styles. It's based on `jsPdf`.
[https://app.zenhub.com/files/439477060/b995a926-6cb8-4a61-8483-9da58c937721/download](https://app.zenhub.com/files/439477060/b995a926-6cb8-4a61-8483-9da58c937721/download). 

3. I also tested other pdf generation libraries such as [pdfMake](http://pdfmake.org/#/), [react-pdf](https://react-pdf.org/) and [pdfkit](https://pdfkit.org/). I could not have them generate a pdf out of HTML for this project. Or in pdfmake case, it was basic and did not include styles at all.

4. I found a paid library [kendo](https://www.telerik.com/kendo-react-ui/components/pdfprocessing/) that was able to generate a pdf with no page break issue and has the BCSans font, though the issue with the icon still exists. I did not look into fixing the issue with the icon with this library since was not sure if a non-opensource library with a license is what you want for this project. The [pricing is here](https://www.telerik.com/kendo-react-ui/pricing/).
[https://app.zenhub.com/files/439477060/3fc922af-9068-4bfe-92f3-c888eec7cd85/download](https://app.zenhub.com/files/439477060/3fc922af-9068-4bfe-92f3-c888eec7cd85/download)

5. Finally I found a library that checks all boxes (almost) and it is opensource and free, (html2pdf)[https://ekoopmans.github.io/html2pdf.js/]. It fixes the issues with page breaks, BCSans font, and icons. It uses a different approach comparing others, generating the pdf using images instead of texts. So, the pdf texts are not selectable -- the only issue I found here.
[https://app.zenhub.com/files/439477060/959bad6b-d2c7-487a-b28f-029800e3fefe/download](https://app.zenhub.com/files/439477060/959bad6b-d2c7-487a-b28f-029800e3fefe/download)

**Comment by Stella-Archer** [comment]
I've had a quick look, option 5 looks really good as 'image only' might be more of a feature than an bug, I will test a bit more this afternoon

**Comment by Stella-Archer** [comment]
It looks really good in print format to
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/be2cd2c5-f865-4fb3-9bf7-4593f77a884d)
1/ I wonder about what it looks like when you fill out info
2/ I'm not sure if the file size is a deal breaker, because it's and image it's bloated up to 3.5MB, is that too much for mail servers ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/de79ea8e-b10b-4a5a-adf9-4d63acc08d90)

**Comment by Abuchana** [comment]
Team has decided to implement sample 2 (2.1 MB)

**Comment by Stella-Archer** [comment]
I've been having an issue getting into dev :( ![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/82ba2002-241a-427d-83d9-2026f1be0814) is it just me?

**Comment by iman-jamali-fw** [comment]
@Stella-Archer I believe it was a temporary outage from IDIR. Should be able to log in now. Can you please try again? Thanks

**Comment by HasanSifat** [comment]
I can get back into the Dev environment now. Looks like the pdf generator is also working smoothly with a pdf generated of 1.9MB in size.
