### ISSUE TITLE
TOOL: Forms Designer Edit Mode Time Out Issue

### ISSUE THREAD

**Issue by MissionT** [bcgov/digital-journeys#793]
Background: As a forms designer, I would like to edit a form without having to remember to save the form edits every 20-30 seconds. What often happens when I have to design/implement a more complex design  such as  adding component logic, I will forget to save within 20-30 seconds and lose all my work. The form page will freeze and the designer must close or refresh the page and start over. 
 
Steps to Reproduce: Go into Edit mode into any environment  such as test or dev and edit a form where it does not time out and freeze every 20-30 seconds. 
 
Actual Behavior: I think the time-out occurred after there was big update to the form. 
 
Expected Behaviour: The forms designer should not have to preoccupied with saving a  form every 20 seconds when in design mode and trying to analyze how to design  the form at the same time. 
 
Environment: both test and dev. 
It would be nice to have this fixed before the Mat/Pat form needs to be designed due it's complexity.

**Comment by fazil-ey** [comment]
check out #137

**Comment by iman-jamali-fw** [comment]
**The issue:**
 The issue happens when the form designer is in edit mode and has a component open to edit, in this situation once the token refreshes (every 5 minutes with the current configuration), the `save` `remove` and `cancel` buttons on the editing component will be no longer responsive.

**Fix:**
I suspect the issue should have something to do with [Edit.js] (https://github.com/bcgov/digital-journeys/blob/main/forms-flow-web/src/components/Form/Item/Edit.js) or the way token is refreshed in [UserService.js](https://github.com/bcgov/digital-journeys/blob/main/forms-flow-web/src/services/UserService.js). However, I didn't find any customization from our end to interfere with way these two components work. Lates AOT version also is as same as what we have at DGJ.



**Workaround**
Increasing the [Access Token Lifespan in the Keycloak Real Settings](https://keycloak.freshworks.club/auth/admin/master/console/#/realms/psa-digital-journey-local/token-settings) will give the designer more time to save their work before the editing component become unresponsive.

**Long-term fix**
I'd suggest creating an issue on AOT to see if they can fix it.

**Comment by iman-jamali-fw** [comment]
Posted the issue on Rocket Chat's formsflow channel (https://chat.developer.gov.bc.ca/channel/formsflow).

**Comment by iman-jamali-fw** [comment]
@Stella-Archer  I increased the `Access Token Lifespan` from 5 minutes to 2 hours on DEV and TEST.
