### ISSUE TITLE
Ability to upload attachments

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#94]
As a BC Gov Employee (or Supervisor) I can upload attachments to forms and have them be saved so that I can provide additional information.

**A/C**

- Can upload a file
- File upload validation:
  - Files Types: _.eml, .pdf, common image formats_ set as defaults (configurable in the form builder for the field)
  - Max File Size: _10 MB_ set as default (configurable in the form builder for the field)

**Dev Notes**
- Determine where we want to store the attachment. If we store it with the form then it will be loaded every time the form gets loaded.

**Notes**
- Using Base64 storage

**Comment by simensma-fresh** [comment]
**Result of spike into storage options**
By default, files are stored as base64 encoded strings on the Submission object itself, which means that any uploaded files will be loaded when a submission is viewed - which can cause significant lag when loading a submission.

Form.io has provided a compatible Open Source upload server we can spin up in order to support file uploads outside the DB: https://github.com/formio/formio-upload. I've tested this out locally, and it works out of the box.

By default, it supports File System storage - but with a bit of effort we could set up an integration with the OCIO Object Storage. https://developer.gov.bc.ca/Persistent-Storage-Services
