### ISSUE TITLE
Mat/Pat : Data retention

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#962]
Forms should be retained for - 

- Drafts - 60 days from last access
- Submitted forms 
     - 3 years  (2 months before starting leave + longest possible leave + 6 or length of leave deferral)  
     - OR since its in CRM it can be much shorter. 
     - On DJ for supervisor/applicant - How long do we allow edits, how long allow do we allow viewing, how long before we delete

**Comment by Stella-Archer** [comment]
@bhumin-fw could you get an estimate for us thx!

**Comment by iman-jamali-fw** [comment]
@Stella-Archer @fazil-ey 
Could you please clarify what you mean by "Draft"? Are you referring to the forms that a user has saved but never submitted, which can be found under the Draft Forms (`/draft`) page? Or, are you talking about the initially submitted forms that have yet to be validated or processed by a manager, and hence, appear on the Submitted Forms page?

**Comment by MeghanStothers** [comment]
We estimate the longest leave would be 3 years

**Comment by MeghanStothers** [comment]
@fazil-ey Hi there - I am looking at this ticket and will confirm to confirm this number. How did we get the 3 years? I will start the conversation with Connie and suggest we add language to the manager/employee email similar to the one in Telework - "store your document according to your ministry specific guidelines..."

**Comment by MeghanStothers** [comment]
@fazil-ey The retention schedule will be included in the PIA and I'd like to make sure we understand the 3 years
Someone apply for leave would apply (max) 2 months before leave + 18 months longest leave + 6 months after returning from leave = 26 months (instead of 3 years). 
If the submission goes onto the CRM, would the last version also be stored on the DJ platform? How would we know when someone has returned from leave or is this 3 years an arbitrary date? What if they went on a second leave in short timeline? Would they be able to complete a new digital Journey?

**Comment by MeghanStothers** [comment]
Decision made at November 16 meeting with form owner/Connie Der of retention schedule = 3 years/36 months
