### ISSUE TITLE
Telework form Clients receive: Internal Server Error Message 

### ISSUE THREAD

**Issue by chriscaldwell-psa** [bcgov/digital-journeys#965]
Background: Telework Form Impacting several clients - Internal Server Error . The issue started on Monday March 6th 
 
Steps to Reproduce: Submit a  form and have an approver complete the approval process. User should be able to login. 
 
Actual Behavior:  Supervisor receives an error message page (see image below) and cannot access the forms portal. See the 2 screenshots below.
 
Expected Behaviour: Approval process by the supervisor/manager should allow  the form to load for approval
 
 
Environment: Prod

![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/6d73a4d7-cacc-4ff1-a592-4a3aacfee71c)

![image.png](https://images.zenhubusercontent.com/62eafeafcc2f007b1446cbd1/c4b2c07f-c39b-4519-aeec-86f21ebf1dee)

**Comment by iman-jamali-fw** [comment]
I wasn't able to reproduce the issue but I believe it is rooted in the recent Keycloak changes in the Gold BCGov Keycloak instance that we're using. There was a number of issues reported since March 3rd in [Rocket chat SSO channel](https://chat.developer.gov.bc.ca/channel/sso).

Today (March 7th), they're deploying a fix that I hope fixes our recent "Internal Server Error".

As the next steps, I suggest asking clients to revisit the links in their emails tomorrow (March 8th) after the fix is deployed.

**Comment by iman-jamali-fw** [comment]
This issue is caused by our recent IDIR user migration. Some of the managers (50 so far) were affected. There is a bug in the Telework manager assignment that does not let some managers in the system.

I found out that our recent IDIR user migration messed with some of our managers (about 50 of them). Turns out, there's a bug in the Telework manager assignment that's keeping some managers out of the system. I'm on it, though! Working to fix the problem and get all those managers back in the game ASAP.

What's going on exactly?
Well, it seems like Keycloak is having trouble merging the accounts of managers who are both users of DGJ and who didn't log in after the recent IDIR migration. This becomes a problem when an employee assigns a submission to them as their managers.

So, what's the solution?
To fix this, we need to merge the duplicate Keycloak accounts and prevent any further duplicate account creation. This can be achieved by taking action in both Camunda and Keycloak.

**Comment by MeghanStothers** [comment]
Iman will run the fix this morning and let the Dj team know.

**Comment by MeghanStothers** [comment]
@iman-jamali-fw Did we have any success with this fix?

**Comment by iman-jamali-fw** [comment]
@MeghanStothers 
It should be done in the next two hours. I was testing the fix on DEV, now running it on PROD. I will update you soon.

**Comment by MeghanStothers** [comment]
Thanks Iman - we're getting messages. For now, I will hold off on adding a "fix in progress" message in hopes we'll squash this bug. Thanks for your persistence

**Comment by iman-jamali-fw** [comment]
@MeghanStothers 

All the affected users' access was restored and they should be able to log in and review the submissions.

In the meantime, I'll work to fix the cause of the issue to make sure it doesn't cause the same issue for other users. Will update soon
